### ISSUE TITLE
Test production.ini in CircleCI

### ISSUE THREAD

**Issue by zupo** [niteoweb/pyramid-realworld-example-app#27]
Uncomment this section in CircleCI config: https://github.com/niteoweb/pyramid-realworld-example-app/blob/master/.circleci/config.yml#L88

It's commented out because when I was configuring CircleCI I did not yet have `production.ini` in a working state.

**Comment by zupo** [comment]
@MatthewWilkes: can you take a look at this one as well?

**Comment by MatthewWilkes** [comment]
Sure. Do I need some access to Circle to be able to test this?

**Comment by zupo** [comment]
I think you access it with your GitHub account? Does this open for you? 
 https://circleci.com/gh/niteoweb/pyramid-realworld-example-app

**Comment by MatthewWilkes** [comment]
Yep, I managed to get in in the end. I've submitted #31 for this.
