### ISSUE TITLE
Validation for `email` field is missing 

### ISSUE THREAD

**Issue by enkidulan** [niteoweb/pyramid-realworld-example-app#33]
In [NewUser specs](https://github.com/niteoweb/pyramid-realworld-example-app/blob/ffdab238bd35d32346f42b09a1303f22a9ba5580/src/conduit/openapi.yaml#L664) `email` field is missing `format` which means that email has no validation whatsoever.

**Comment by zupo** [comment]
I'm torn between two options:
* Keep the `openapi.yaml` as it is provided by RealWorld, to keep future compatibility and updates easier.
* Fix obvious shortcomings such as the one you mentioned. 

Thoughts?

**Comment by enkidulan** [comment]
That is a bug, at least you can create an issue that provided specs are
missing some points.

**Comment by zupo** [comment]
> That is a bug, at least you can create an issue that provided specs are
missing some points.

Not realistic. The spec at https://github.com/gothinkster/realworld/blob/master/api/swagger.json has not changed in 2 years. If it did, all reference implementations would have to be updated, so I don't see that happening.

**Comment by zupo** [comment]
Not likely the underlying spec will change, so I'm closing this.
