### ISSUE TITLE
Optimize nix build

### ISSUE THREAD

**Issue by sayanarijit** [niteoweb/pyramid-realworld-example-app#88]
Due to a [known issue](https://github.com/NixOS/nix/issues/719) nix garbage collector is collecting more packages than it should. The suggested solution is running `ln -sfv /root/.cache/nix/tarballs/* /nix/var/nix/gcroots/auto` before collecting garbage. However, that doesn't seem to fix the issue.

**Comment by jared-w** [comment]
Does [this solution](https://github.com/NixOS/nix/issues/954#issuecomment-449626884) work for you? I've seen a variant of it used elsewhere (eg in iohk's codebase) as `ifdPins`

```nix
  mkPins = inputs:
    pkgs.runCommand "ifd-pins" { } ''
      mkdir $out
      cd $out
      ${lib.concatMapStringsSep "\n" (i: "ln -sv ${i.value} ${i.key}")
      (lib.attrValues
        (lib.mapAttrs (key: value: { inherit key value; }) inputs))}
    '';
```

**Comment by sayanarijit** [comment]
Trying a fix in https://github.com/niteoweb/pyramid-realworld-example-app/pull/104

**Comment by sayanarijit** [comment]
i.e. using `NIX_BUILD_SHELL=/nix/var/nix/profiles/default/bin/bash`

**Comment by sayanarijit** [comment]
Seems to be working.
